export default {
  default: {
    font: "Body",
    fontSize: 9,
    lineHeight: 1.15,
  },
  separator: {
    lineWidth: 0.5,
    lineColor: "#aaaaaa",
    margin: [0, 36],
  },
  code: {
    font: "Monospaced",
    fontSize: 8,
    background: "#eeeeee",
    bold: false,
  },
  bold: { bold: true },
  italics: { italics: true },
  left: { alignment: "left" },
  right: { alignment: "right" },
  center: { alignment: "center" },
  small: { fontSize: 7, color: "#888888", lineHeight: 1.1 },
  link: { decoration: "underline" },
  p: { margin: [0, 0, 0, 6] },
  ul: { margin: [0, 0, 0, 9] },
  ol: { margin: [0, 0, 0, 9] },
  li: { margin: [0, 3, 0, 0] },
  ul_inner: { margin: [0, -6, 0, 0] },
  ol_inner: { margin: [0, -6, 0, 0] },
  img: { alignment: "center" },
  caption: { alignment: "center", font: "Headings", fontSize: 8, margin: [0, 0, 0, 12] },
  pre: { fillColor: "#eeeeee", lineHeight: 1, margin: [6, 4.5] },
  unbreakable: { unbreakable: true },
  nomargin: { margin: [0, 0] },
  block: { margin: [6, 4.5] },
  block_outer: { margin: [0, 6, 0, 12] },
  footer: { fontSize: 8 },
  note: { fillColor: "#dddddd", margin: [6, 4.5] },
  table: { margin: [0, 6, 0, 12] },
  tableHeader: { fillColor: "#dddddd", font: "Headings", bold: true },
  defs: { table: true, layout: "default", widths: [100, "*"] },
  toc: { layout: "toc", margin: [0, 18], widths: ["*", 30], lineHeight: 1 },
  h1: {
    font: "Headings Light",
    fontSize: 24,
    lineHeight: 0.9,
    characterSpacing: -1,
    margin: [0, 12, 0, 24],
  },
  autonum_h1: {
    font: "Headings",
    fontSize: 36,
    bold: true,
  },
  toc1: {
    bold: true,
  },
  h2: {
    font: "Headings",
    fontSize: 12,
    bold: true,
    margin: [0, 12, 0, 4],
  },
  toc2: {
    margin: [8, 0, 0, 0],
  },
  h3: {
    font: "Headings",
    fontSize: 10,
    bold: true,
    margin: [0, 12, 0, 4],
  },
  toc3: {
    margin: [16, 0, 0, 0],
  },
  h4: {
    font: "Headings Bold",
    fontSize: 9,
    bold: true,
    margin: [0, 6, 0, 0],
  },
};
